<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-9837-1648544575/blob/main/ANN_Categorical%20Assignment%203%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as  pd
pd.options.display.float_format = '{:.2f}'.format


In [ ]:
dataset = pd.read_csv(r"c:\users\prads\OneDrive\Desktop\fish.csv")

In [ ]:
dataset.head(5)

Weight  Length1  Length2  Length3   Height   Width Species
0   242.0     23.2     25.4     30.0  11.5200  4.0200   Bream
1   290.0     24.0     26.3     31.2  12.4800  4.3056   Bream
2   340.0     23.9     26.5     31.1  12.3778  4.6961   Bream
3   363.0     26.3     29.0     33.5  12.7300  4.4555   Bream
4   430.0     26.5     29.0     34.0  12.4440  5.1340   Bream

In [ ]:
dataset.isnull().any()

Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
Species    False
dtype: bool

In [ ]:
dataset.head()

Weight  Length1  Length2  Length3   Height   Width Species
0   242.0     23.2     25.4     30.0  11.5200  4.0200   Bream
1   290.0     24.0     26.3     31.2  12.4800  4.3056   Bream
2   340.0     23.9     26.5     31.1  12.3778  4.6961   Bream
3   363.0     26.3     29.0     33.5  12.7300  4.4555   Bream
4   430.0     26.5     29.0     34.0  12.4440  5.1340   Bream

In [ ]:
x = dataset.iloc[:,0:6].values
y = dataset.iloc[:,6:].values

In [ ]:
dataset.head(5)

Weight  Length1  Length2  Length3   Height   Width Species
0   242.0     23.2     25.4     30.0  11.5200  4.0200   Bream
1   290.0     24.0     26.3     31.2  12.4800  4.3056   Bream
2   340.0     23.9     26.5     31.1  12.3778  4.6961   Bream
3   363.0     26.3     29.0     33.5  12.7300  4.4555   Bream
4   430.0     26.5     29.0     34.0  12.4440  5.1340   Bream

In [ ]:
type(y)

numpy.ndarray

In [ ]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [ ]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [ ]:
# 0 - Bream , 1 = Parkki 2 = perch 3 = pike 4 = Roach 5 = Smelt 6 = Whitefish

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder = "passthrough")
y = ct.fit_transform(y)

In [ ]:
y = y.toarray()

In [ ]:
type(y)

numpy.ndarray

In [ ]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
y.shape

(159, 7)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 1)

In [ ]:
x_train.shape

(111, 6)

In [ ]:
y_train.shape

(111, 7)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


In [ ]:
categorical = Sequential()

In [ ]:
categorical.add(Dense(units = 6 , kernel_initializer = "random_uniform",activation ="relu"))

In [ ]:
categorical.add(Dropout(0.2))

In [ ]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [ ]:
categorical.add(Dropout(0.2))

In [ ]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [ ]:
categorical.add(Dropout(0.2))

In [ ]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [ ]:
categorical.add(Dense(units = 7 , kernel_initializer = "random_uniform",activation ="softmax"))

In [ ]:
categorical.compile(optimizer = "rmsprop",loss="categorical_crossentropy" ,metrics = ["accuracy"])

In [ ]:
history = categorical.fit(x_train,y_train, batch_size =128,epochs = 1000, validation_data = (x_test,y_test))

Epoch 1/1000
1/1 [==============================] - 0s 170ms/step - loss: 0.6441 - accuracy: 0.7838 - val_loss: 1.8517 - val_accuracy: 0.8125
Epoch 2/1000
1/1 [==============================] - 0s 88ms/step - loss: 0.6204 - accuracy: 0.7928 - val_loss: 1.8628 - val_accuracy: 0.8125
Epoch 3/1000
1/1 [==============================] - 0s 81ms/step - loss: 0.4919 - accuracy: 0.8198 - val_loss: 1.8606 - val_accuracy: 0.8125
Epoch 4/1000
1/1 [==============================] - 0s 79ms/step - loss: 0.5554 - accuracy: 0.8288 - val_loss: 1.8612 - val_accuracy: 0.8125
Epoch 5/1000
1/1 [==============================] - 0s 75ms/step - loss: 0.5019 - accuracy: 0.8468 - val_loss: 1.8746 - val_accuracy: 0.8125
Epoch 6/1000
1/1 [==============================] - 0s 84ms/step - loss: 0.5044 - accuracy: 0.8559 - val_loss: 1.8675 - val_accuracy: 0.7917
Epoch 7/1000
1/1 [==============================] - 0s 80ms/step - loss: 0.5431 - accuracy: 0.8108 - val_loss: 1.9022 - val_accuracy: 0.7917
Epoch 8/1000

1/1 [==============================] - 0s 72ms/step - loss: 0.5714 - accuracy: 0.7838 - val_loss: 2.2155 - val_accuracy: 0.7708
Epoch 59/1000
1/1 [==============================] - 0s 79ms/step - loss: 0.5954 - accuracy: 0.7928 - val_loss: 2.1715 - val_accuracy: 0.7917
Epoch 60/1000
1/1 [==============================] - 0s 67ms/step - loss: 0.5527 - accuracy: 0.8378 - val_loss: 2.1151 - val_accuracy: 0.7917
Epoch 61/1000
1/1 [==============================] - 0s 69ms/step - loss: 0.6139 - accuracy: 0.8018 - val_loss: 2.1287 - val_accuracy: 0.7708
Epoch 62/1000
1/1 [==============================] - 0s 73ms/step - loss: 0.6103 - accuracy: 0.8108 - val_loss: 1.3755 - val_accuracy: 0.7708
Epoch 63/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.6958 - accuracy: 0.8108 - val_loss: 1.4436 - val_accuracy: 0.7708
Epoch 64/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.6401 - accuracy: 0.7928 - val_loss: 1.4372 - val_accuracy: 0.7708
Epoch 65/1000
1/1 [=

1/1 [==============================] - 0s 100ms/step - loss: 0.5601 - accuracy: 0.7928 - val_loss: 1.4845 - val_accuracy: 0.7708
Epoch 116/1000
1/1 [==============================] - 0s 107ms/step - loss: 0.4996 - accuracy: 0.8559 - val_loss: 1.4895 - val_accuracy: 0.7708
Epoch 117/1000
1/1 [==============================] - 0s 94ms/step - loss: 0.6248 - accuracy: 0.7838 - val_loss: 1.4516 - val_accuracy: 0.7708
Epoch 118/1000
1/1 [==============================] - 0s 95ms/step - loss: 0.4859 - accuracy: 0.8288 - val_loss: 1.5908 - val_accuracy: 0.7708
Epoch 119/1000
1/1 [==============================] - 0s 85ms/step - loss: 0.6204 - accuracy: 0.7838 - val_loss: 1.5214 - val_accuracy: 0.7917
Epoch 120/1000
1/1 [==============================] - 0s 117ms/step - loss: 0.5279 - accuracy: 0.8378 - val_loss: 1.5358 - val_accuracy: 0.7708
Epoch 121/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.5627 - accuracy: 0.8468 - val_loss: 1.4907 - val_accuracy: 0.7708
Epoch 122/1

1/1 [==============================] - 0s 89ms/step - loss: 0.5625 - accuracy: 0.8198 - val_loss: 1.5110 - val_accuracy: 0.7708
Epoch 173/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.5875 - accuracy: 0.8108 - val_loss: 1.5136 - val_accuracy: 0.7708
Epoch 174/1000
1/1 [==============================] - 0s 116ms/step - loss: 0.6294 - accuracy: 0.8018 - val_loss: 1.5361 - val_accuracy: 0.7917
Epoch 175/1000
1/1 [==============================] - 0s 143ms/step - loss: 0.5878 - accuracy: 0.8288 - val_loss: 1.5518 - val_accuracy: 0.7708
Epoch 176/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.5655 - accuracy: 0.8108 - val_loss: 1.5686 - val_accuracy: 0.7917
Epoch 177/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.5121 - accuracy: 0.8108 - val_loss: 1.5723 - val_accuracy: 0.7708
Epoch 178/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.6586 - accuracy: 0.7838 - val_loss: 1.5455 - val_accuracy: 0.7917
Epoch 17

1/1 [==============================] - 0s 129ms/step - loss: 0.4343 - accuracy: 0.8468 - val_loss: 1.7039 - val_accuracy: 0.7708
Epoch 230/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.6667 - accuracy: 0.8198 - val_loss: 1.8444 - val_accuracy: 0.7708
Epoch 231/1000
1/1 [==============================] - 0s 119ms/step - loss: 0.5490 - accuracy: 0.8198 - val_loss: 1.8416 - val_accuracy: 0.7708
Epoch 232/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.5399 - accuracy: 0.8108 - val_loss: 1.8836 - val_accuracy: 0.7708
Epoch 233/1000
1/1 [==============================] - 0s 110ms/step - loss: 0.5973 - accuracy: 0.8108 - val_loss: 1.8488 - val_accuracy: 0.7917
Epoch 234/1000
1/1 [==============================] - 0s 98ms/step - loss: 0.5188 - accuracy: 0.8198 - val_loss: 1.7988 - val_accuracy: 0.8125
Epoch 235/1000
1/1 [==============================] - 0s 116ms/step - loss: 0.6587 - accuracy: 0.7658 - val_loss: 1.8669 - val_accuracy: 0.7708
Epoch 23

1/1 [==============================] - 0s 112ms/step - loss: 0.4936 - accuracy: 0.8288 - val_loss: 1.5182 - val_accuracy: 0.7917
Epoch 287/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.4824 - accuracy: 0.8468 - val_loss: 1.5498 - val_accuracy: 0.7917
Epoch 288/1000
1/1 [==============================] - 0s 107ms/step - loss: 0.6011 - accuracy: 0.8288 - val_loss: 1.6122 - val_accuracy: 0.7708
Epoch 289/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.5666 - accuracy: 0.8018 - val_loss: 1.5679 - val_accuracy: 0.8125
Epoch 290/1000
1/1 [==============================] - 0s 106ms/step - loss: 0.5278 - accuracy: 0.8198 - val_loss: 1.5592 - val_accuracy: 0.7917
Epoch 291/1000
1/1 [==============================] - 0s 132ms/step - loss: 0.6553 - accuracy: 0.7838 - val_loss: 1.5256 - val_accuracy: 0.7917
Epoch 292/1000
1/1 [==============================] - 0s 131ms/step - loss: 0.5705 - accuracy: 0.8108 - val_loss: 1.7746 - val_accuracy: 0.7917
Epoch 2

Epoch 343/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.4891 - accuracy: 0.8559 - val_loss: 1.7869 - val_accuracy: 0.7917
Epoch 344/1000
1/1 [==============================] - 0s 101ms/step - loss: 0.5960 - accuracy: 0.8018 - val_loss: 1.7944 - val_accuracy: 0.7917
Epoch 345/1000
1/1 [==============================] - 0s 81ms/step - loss: 0.6974 - accuracy: 0.8018 - val_loss: 1.7895 - val_accuracy: 0.7917
Epoch 346/1000
1/1 [==============================] - 0s 97ms/step - loss: 0.7316 - accuracy: 0.8018 - val_loss: 1.7780 - val_accuracy: 0.7708
Epoch 347/1000
1/1 [==============================] - 0s 208ms/step - loss: 0.5209 - accuracy: 0.8468 - val_loss: 1.8078 - val_accuracy: 0.7708
Epoch 348/1000
1/1 [==============================] - 0s 100ms/step - loss: 0.5950 - accuracy: 0.8108 - val_loss: 1.8212 - val_accuracy: 0.7708
Epoch 349/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.7001 - accuracy: 0.8108 - val_loss: 1.7768 - val_accuracy: 0.7

1/1 [==============================] - 0s 87ms/step - loss: 0.5561 - accuracy: 0.8108 - val_loss: 2.0408 - val_accuracy: 0.8125
Epoch 401/1000
1/1 [==============================] - 0s 93ms/step - loss: 0.5486 - accuracy: 0.7838 - val_loss: 2.1292 - val_accuracy: 0.7708
Epoch 402/1000
1/1 [==============================] - 0s 96ms/step - loss: 0.5403 - accuracy: 0.8288 - val_loss: 2.1617 - val_accuracy: 0.7917
Epoch 403/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.5608 - accuracy: 0.8108 - val_loss: 2.0374 - val_accuracy: 0.8125
Epoch 404/1000
1/1 [==============================] - 0s 87ms/step - loss: 0.6350 - accuracy: 0.7748 - val_loss: 2.1218 - val_accuracy: 0.7708
Epoch 405/1000
1/1 [==============================] - 0s 87ms/step - loss: 0.5531 - accuracy: 0.8378 - val_loss: 2.1305 - val_accuracy: 0.7708
Epoch 406/1000
1/1 [==============================] - 0s 99ms/step - loss: 0.6263 - accuracy: 0.7928 - val_loss: 2.1907 - val_accuracy: 0.7708
Epoch 407/1000

1/1 [==============================] - 0s 126ms/step - loss: 0.4477 - accuracy: 0.8468 - val_loss: 1.9789 - val_accuracy: 0.7708
Epoch 458/1000
1/1 [==============================] - 0s 98ms/step - loss: 0.6147 - accuracy: 0.7748 - val_loss: 1.9518 - val_accuracy: 0.7708
Epoch 459/1000
1/1 [==============================] - 0s 97ms/step - loss: 0.5760 - accuracy: 0.7928 - val_loss: 1.9714 - val_accuracy: 0.7708
Epoch 460/1000
1/1 [==============================] - 0s 96ms/step - loss: 0.5274 - accuracy: 0.8378 - val_loss: 1.9865 - val_accuracy: 0.7917
Epoch 461/1000
1/1 [==============================] - 0s 85ms/step - loss: 0.5558 - accuracy: 0.8198 - val_loss: 1.8963 - val_accuracy: 0.8125
Epoch 462/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.5783 - accuracy: 0.8018 - val_loss: 1.9513 - val_accuracy: 0.8125
Epoch 463/1000
1/1 [==============================] - 0s 93ms/step - loss: 0.6046 - accuracy: 0.8108 - val_loss: 1.9948 - val_accuracy: 0.7917
Epoch 464/10

1/1 [==============================] - 0s 72ms/step - loss: 0.5336 - accuracy: 0.8378 - val_loss: 1.3013 - val_accuracy: 0.7708
Epoch 515/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.7602 - accuracy: 0.7568 - val_loss: 1.3273 - val_accuracy: 0.7917
Epoch 516/1000
1/1 [==============================] - 0s 123ms/step - loss: 0.6003 - accuracy: 0.8378 - val_loss: 1.3367 - val_accuracy: 0.7708
Epoch 517/1000
1/1 [==============================] - 0s 116ms/step - loss: 0.5560 - accuracy: 0.8468 - val_loss: 1.3353 - val_accuracy: 0.7708
Epoch 518/1000
1/1 [==============================] - 0s 164ms/step - loss: 0.5667 - accuracy: 0.8108 - val_loss: 1.3730 - val_accuracy: 0.7917
Epoch 519/1000
1/1 [==============================] - 0s 169ms/step - loss: 0.7246 - accuracy: 0.8198 - val_loss: 1.2770 - val_accuracy: 0.8125
Epoch 520/1000
1/1 [==============================] - 0s 251ms/step - loss: 0.5920 - accuracy: 0.8108 - val_loss: 1.2854 - val_accuracy: 0.8125
Epoch 52

1/1 [==============================] - 0s 136ms/step - loss: 0.5606 - accuracy: 0.8288 - val_loss: 1.5685 - val_accuracy: 0.7917
Epoch 572/1000
1/1 [==============================] - 0s 140ms/step - loss: 0.6042 - accuracy: 0.8018 - val_loss: 1.5654 - val_accuracy: 0.7708
Epoch 573/1000
1/1 [==============================] - 0s 94ms/step - loss: 0.5467 - accuracy: 0.8018 - val_loss: 1.5399 - val_accuracy: 0.7917
Epoch 574/1000
1/1 [==============================] - 0s 100ms/step - loss: 0.5180 - accuracy: 0.8559 - val_loss: 1.5800 - val_accuracy: 0.7708
Epoch 575/1000
1/1 [==============================] - 0s 91ms/step - loss: 0.5198 - accuracy: 0.8198 - val_loss: 1.4945 - val_accuracy: 0.8333
Epoch 576/1000
1/1 [==============================] - 0s 87ms/step - loss: 0.6434 - accuracy: 0.7928 - val_loss: 1.5550 - val_accuracy: 0.8125
Epoch 577/1000
1/1 [==============================] - 0s 95ms/step - loss: 0.5770 - accuracy: 0.7838 - val_loss: 1.5815 - val_accuracy: 0.7917
Epoch 578/1

1/1 [==============================] - 0s 86ms/step - loss: 0.6092 - accuracy: 0.8378 - val_loss: 1.2626 - val_accuracy: 0.7917
Epoch 629/1000
1/1 [==============================] - 0s 96ms/step - loss: 0.5297 - accuracy: 0.8018 - val_loss: 1.3238 - val_accuracy: 0.7917
Epoch 630/1000
1/1 [==============================] - 0s 87ms/step - loss: 0.5750 - accuracy: 0.8198 - val_loss: 1.2719 - val_accuracy: 0.8125
Epoch 631/1000
1/1 [==============================] - 0s 87ms/step - loss: 0.5907 - accuracy: 0.8378 - val_loss: 1.2226 - val_accuracy: 0.8125
Epoch 632/1000
1/1 [==============================] - 0s 85ms/step - loss: 0.6527 - accuracy: 0.7838 - val_loss: 1.2857 - val_accuracy: 0.7917
Epoch 633/1000
1/1 [==============================] - 0s 92ms/step - loss: 0.5309 - accuracy: 0.8468 - val_loss: 1.2628 - val_accuracy: 0.7917
Epoch 634/1000
1/1 [==============================] - 0s 88ms/step - loss: 0.4869 - accuracy: 0.8108 - val_loss: 1.2932 - val_accuracy: 0.7917
Epoch 635/1000

1/1 [==============================] - 0s 215ms/step - loss: 0.5329 - accuracy: 0.8378 - val_loss: 1.6396 - val_accuracy: 0.7708
Epoch 686/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.5389 - accuracy: 0.8649 - val_loss: 1.5963 - val_accuracy: 0.7708
Epoch 687/1000
1/1 [==============================] - 0s 109ms/step - loss: 0.4769 - accuracy: 0.8468 - val_loss: 1.6283 - val_accuracy: 0.7917
Epoch 688/1000
1/1 [==============================] - 0s 99ms/step - loss: 0.4927 - accuracy: 0.8559 - val_loss: 1.5504 - val_accuracy: 0.7708
Epoch 689/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.6623 - accuracy: 0.8468 - val_loss: 1.5772 - val_accuracy: 0.7708
Epoch 690/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.6004 - accuracy: 0.7928 - val_loss: 1.6220 - val_accuracy: 0.7708
Epoch 691/1000
1/1 [==============================] - 0s 97ms/step - loss: 0.5157 - accuracy: 0.8559 - val_loss: 1.5536 - val_accuracy: 0.8125
Epoch 692/10

1/1 [==============================] - 0s 92ms/step - loss: 0.6409 - accuracy: 0.8018 - val_loss: 1.4333 - val_accuracy: 0.7917
Epoch 743/1000
1/1 [==============================] - 0s 101ms/step - loss: 0.6933 - accuracy: 0.7928 - val_loss: 1.4184 - val_accuracy: 0.7917
Epoch 744/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.5962 - accuracy: 0.7748 - val_loss: 1.4273 - val_accuracy: 0.7917
Epoch 745/1000
1/1 [==============================] - 0s 98ms/step - loss: 0.5414 - accuracy: 0.8018 - val_loss: 1.4537 - val_accuracy: 0.7917
Epoch 746/1000
1/1 [==============================] - 0s 92ms/step - loss: 0.7144 - accuracy: 0.8018 - val_loss: 1.3633 - val_accuracy: 0.8125
Epoch 747/1000
1/1 [==============================] - 0s 97ms/step - loss: 0.6702 - accuracy: 0.7658 - val_loss: 1.4718 - val_accuracy: 0.7708
Epoch 748/1000
1/1 [==============================] - 0s 92ms/step - loss: 0.5575 - accuracy: 0.8108 - val_loss: 1.4207 - val_accuracy: 0.7708
Epoch 749/100

1/1 [==============================] - 0s 88ms/step - loss: 0.4807 - accuracy: 0.8288 - val_loss: 1.6431 - val_accuracy: 0.7917
Epoch 800/1000
1/1 [==============================] - 0s 96ms/step - loss: 0.5873 - accuracy: 0.8288 - val_loss: 1.6876 - val_accuracy: 0.7708
Epoch 801/1000
1/1 [==============================] - 0s 91ms/step - loss: 0.5979 - accuracy: 0.8198 - val_loss: 1.6575 - val_accuracy: 0.7917
Epoch 802/1000
1/1 [==============================] - 0s 88ms/step - loss: 0.6008 - accuracy: 0.8288 - val_loss: 1.6923 - val_accuracy: 0.7708
Epoch 803/1000
1/1 [==============================] - 0s 97ms/step - loss: 0.5658 - accuracy: 0.8108 - val_loss: 1.6743 - val_accuracy: 0.7917
Epoch 804/1000
1/1 [==============================] - 0s 88ms/step - loss: 0.7641 - accuracy: 0.7928 - val_loss: 1.6832 - val_accuracy: 0.7917
Epoch 805/1000
1/1 [==============================] - 0s 92ms/step - loss: 0.5733 - accuracy: 0.7838 - val_loss: 1.7359 - val_accuracy: 0.7708
Epoch 806/1000

1/1 [==============================] - 0s 89ms/step - loss: 0.5461 - accuracy: 0.8288 - val_loss: 1.9299 - val_accuracy: 0.7708
Epoch 857/1000
1/1 [==============================] - 0s 94ms/step - loss: 0.5241 - accuracy: 0.8288 - val_loss: 1.9539 - val_accuracy: 0.7708
Epoch 858/1000
1/1 [==============================] - 0s 207ms/step - loss: 0.6066 - accuracy: 0.8288 - val_loss: 1.9283 - val_accuracy: 0.7917
Epoch 859/1000
1/1 [==============================] - 0s 83ms/step - loss: 0.6219 - accuracy: 0.7838 - val_loss: 1.9352 - val_accuracy: 0.7708
Epoch 860/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.5948 - accuracy: 0.8288 - val_loss: 1.9658 - val_accuracy: 0.7708
Epoch 861/1000
1/1 [==============================] - 0s 94ms/step - loss: 0.4677 - accuracy: 0.8468 - val_loss: 1.9019 - val_accuracy: 0.7917
Epoch 862/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.5243 - accuracy: 0.8378 - val_loss: 1.9583 - val_accuracy: 0.7708
Epoch 863/100

1/1 [==============================] - 0s 87ms/step - loss: 0.7030 - accuracy: 0.7748 - val_loss: 2.0061 - val_accuracy: 0.7917
Epoch 914/1000
1/1 [==============================] - 0s 99ms/step - loss: 0.5950 - accuracy: 0.8018 - val_loss: 2.0061 - val_accuracy: 0.8125
Epoch 915/1000
1/1 [==============================] - 0s 90ms/step - loss: 0.5932 - accuracy: 0.7838 - val_loss: 2.0458 - val_accuracy: 0.8125
Epoch 916/1000
1/1 [==============================] - 0s 89ms/step - loss: 0.4803 - accuracy: 0.8378 - val_loss: 2.0674 - val_accuracy: 0.8125
Epoch 917/1000
1/1 [==============================] - 0s 85ms/step - loss: 0.4240 - accuracy: 0.8559 - val_loss: 2.0482 - val_accuracy: 0.8333
Epoch 918/1000
1/1 [==============================] - 0s 95ms/step - loss: 0.6178 - accuracy: 0.8198 - val_loss: 2.1094 - val_accuracy: 0.7917
Epoch 919/1000
1/1 [==============================] - 0s 79ms/step - loss: 0.5599 - accuracy: 0.8108 - val_loss: 2.0908 - val_accuracy: 0.7708
Epoch 920/1000

1/1 [==============================] - 0s 102ms/step - loss: 0.7272 - accuracy: 0.7658 - val_loss: 1.6637 - val_accuracy: 0.7708
Epoch 971/1000
1/1 [==============================] - 0s 98ms/step - loss: 0.5534 - accuracy: 0.7928 - val_loss: 1.6166 - val_accuracy: 0.7708
Epoch 972/1000
1/1 [==============================] - 0s 94ms/step - loss: 0.6386 - accuracy: 0.8378 - val_loss: 1.6735 - val_accuracy: 0.7708
Epoch 973/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.5383 - accuracy: 0.7838 - val_loss: 1.6546 - val_accuracy: 0.7917
Epoch 974/1000
1/1 [==============================] - 0s 169ms/step - loss: 0.5909 - accuracy: 0.8108 - val_loss: 1.6325 - val_accuracy: 0.8125
Epoch 975/1000
1/1 [==============================] - 0s 150ms/step - loss: 0.5532 - accuracy: 0.8018 - val_loss: 1.6177 - val_accuracy: 0.7917
Epoch 976/1000
1/1 [==============================] - 0s 135ms/step - loss: 0.5929 - accuracy: 0.8108 - val_loss: 1.6055 - val_accuracy: 0.7917
Epoch 977

In [ ]:
yp = categorical.predict(sc.transform([[120,17.5,19,21.3,8.3922,2.9181]]))

In [ ]:
yp

array([[2.7900047e-03, 5.2574468e-01, 1.2406466e-18, 2.4415867e-01,
        2.1852653e-01, 0.0000000e+00, 8.7801702e-03]], dtype=float32)

In [ ]:
yp>0.5

array([[False,  True, False, False, False, False, False]])

In [ ]:
y p = [0,1,0,0,0,0] # bearm

SyntaxError: invalid syntax (<ipython-input-122-c0b4bc6d55ae>, line 1)

In [ ]:
yp = categorical.predict_classes(sc.transform([[60,17.5,19,21.3,8.3922,20.9181]]))

C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
yp

array([2], dtype=int64)

In [ ]:
yp = categorical.predict(sc.transform([[20,17.5,42.3,134.3,8.3922,0.9181]]))

In [ ]:
print(yp)

[[1. 0. 0. 0. 0. 0. 0.]]


In [ ]:
yp = np.argmax(yp)#[0,0,0,0,1,0] 

In [ ]:
index = ["bearm","parkki","perch","pike","roach","smelt","whitefih"]

In [ ]:
index[yp]

'bearm'

In [ ]:
prediction = index[yp]

In [ ]:
prediction

'whitefih'

In [ ]:
a = np.array([20,2,7,8,10])

In [ ]:
a

array([20,  2,  7,  8, 10])

In [ ]:
np.argmax(a)

0